#include "cpp_emitter.hpp"

#include <algorithm>
#include <concepts>
#include <format>
#include <string_view>
#include <type_traits>
#include <vector>

#include "generator.hpp"
#include "typeformatter.hpp"

#include "tools/sort.hpp"

#include "utils/debug.hpp"

namespace {
	using namespace shade;

	/**
	 * @brief Checks whether any atomic specialization uses a fixed buffer count.
	 *
	 * @param record A `const schema::SchemaAtomicRecord_t&`.
	 * @return A `bool`.
	 */
	[[nodiscard]] bool HasFixedBufferCountParameter(const schema::SchemaAtomicRecord_t& record) {
		return std::ranges::any_of(record.m_Specializations, [](const auto& specialization) {
			const auto* parameters = std::get_if<schema::SchemaAtomicCollectionParameters_t>(&specialization.m_Parameters);
			return parameters && parameters->m_nFixedBufferCount != 0;
		});
	}

} // namespace

void shade::codegen::CCppEmitter::Prologue() {
	m_Generator.StartBlockComment()
	    .NewLine()
	    .Comment(" * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.\n")
	    .Comment(" * This file may be used for educational purposes only.\n")
	    .Comment(" ")
	    .EndBlockComment()
	    .NewLine()
	    .NewLine();

	m_Generator.StartBlockComment()
	    .NewLine()
	    .Comment(" * Link to the SDK generator: https://github.com/arisuwine/shadegenerator\n")
	    .Comment(" * Link to the SDK generator developer: https://github.com/arisuwine\n")
	    .Comment(" ")
	    .EndBlockComment()
	    .NewLine()
	    .NewLine();

	m_Generator.Pragma("once");
	m_Generator.Include("cstdint", EIncludeType::System);
	m_Generator.Include("memory", EIncludeType::System);
	m_Generator.Include("utility", EIncludeType::System).NewLine();
}

void shade::codegen::CCppEmitter::Dependencies(const schema::SchemaDependencies_t& dependencies) {
	bool hasIncludes = false;
	for (const auto& [module, definitions] : tools::GetSortedDependencyGroups(dependencies.m_Definitions)) {
		for (const auto name : definitions) {
			const std::string path = module.empty() ? std::format("shade/sdk/{}.hpp", name) : std::format("shade/sdk/{}/{}.hpp", module, name);
			m_Generator.Include(path, EIncludeType::Local);
			hasIncludes = true;
		}
	}
	if (hasIncludes)
		m_Generator.NewLine();

	const auto declarationGroups = tools::GetSortedDependencyGroups(dependencies.m_Declarations);
	if (declarationGroups.empty())
		return;

	m_Generator
	    .Namespace("shade",
	               [&] {
		               m_Generator.Namespace("sdk", [&] {
			               std::size_t moduleIndex = 0;
			               for (const auto& [module, declarations] : declarationGroups) {
				               auto emitDeclarations = [&] {
					               for (const auto name : declarations) {
						               if (name.ends_with("_t"))
							               m_Generator.StructForwardDeclaration(name);
						               else
							               m_Generator.ClassForwardDeclaration(name);
					               }
				               };

				               if (module.empty())
					               emitDeclarations();
				               else
					               m_Generator.Namespace(module, emitDeclarations);

				               if (++moduleIndex != declarationGroups.size())
					               m_Generator.NewLine();
			               }
		               });
	               })
	    .NewLine();
}

void shade::codegen::CCppEmitter::ClassParameters(const schema::SchemaClassRecord_t& record) {
	m_Generator.StartBlockComment().Comment(" Class Parameters\n");
	m_Generator.Comment(std::format(" * Size: 0x{:x}\n", record.m_Layout.m_nSize));
	m_Generator.Comment(std::format(" * Alignment: 0x{:x}\n", record.m_Layout.m_nAlignment));

	const std::uint32_t flags = record.m_eFlags;
	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_HAS_VTABLE)
		m_Generator.Comment(" * Has VTable\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_IS_ABSTRACT)
		m_Generator.Comment(" * Abstract Class\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_HAS_TRIVIAL_CONSTRUCTOR)
		m_Generator.Comment(" * Has Trivial Constructor\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_HAS_TRIVIAL_DESTRUCTOR)
		m_Generator.Comment(" * Has Trivial Destructor\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_CONSTRUCT_ALLOWED)
		m_Generator.Comment(" * Construct Allowed\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_CONSTRUCT_DISALLOWED)
		m_Generator.Comment(" * Construct Disallowed\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_MODULE_LOCAL_TYPE_SCOPE)
		m_Generator.Comment(" * Module Local Type Scope\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_GLOBAL_TYPE_SCOPE)
		m_Generator.Comment(" * Global Type Scope\n");

	m_Generator.Comment(" ").EndBlockComment().NewLine();
}

void shade::codegen::CCppEmitter::DataMapFields(std::span<const schema::SchemaDataMapFieldRecord_t> fields) {
	if (fields.empty()) {
		m_Generator.Comment("No unique data map fields\n\n");
		return;
	}

	m_Generator.StartBlockComment().Comment(" Data Map Fields\n");
	for (const auto& field : fields) {
		const std::string declaration = m_Formatter.FormatDeclaration(field.m_Type, field.m_szName, field.m_nSizeInBytes);
		m_Generator.Comment(std::format(" * {}; // Offset: 0x{:x}, Size: 0x{:x}, Size In Bytes: 0x{:x}\n", declaration, field.m_nOffset, field.m_nSize,
		                                field.m_nSizeInBytes));
	}

	m_Generator.Comment(" ").EndBlockComment().NewLine().NewLine();
}

std::size_t shade::codegen::CCppEmitter::BaseCursor(const schema::SchemaClassRecord_t& record) const {
	std::size_t nCursor = 0;

	for (std::size_t i = 0; i < record.m_BaseClasses.size(); ++i) {
		const auto&       base       = record.m_BaseClasses[i];
		const std::size_t nSchemaEnd = base.m_nOffset + base.m_nSize;

		if (base.m_nOffset > record.m_Layout.m_nSize || nSchemaEnd > record.m_Layout.m_nSize)
			lg::Warn("emitter", "base '{}' has a range outside class '{}'", base.m_Name.m_szName, record.m_Name.m_szName);

		if (base.m_nOffset != nCursor) {
			lg::Warn("emitter", "base '{}' in '{}' has schema offset 0x{:x}, but packed C++ inheritance places it at expected offset 0x{:x}",
			         base.m_Name.m_szName, record.m_Name.m_szName, base.m_nOffset, nCursor);
			m_Generator.Comment(
			    std::format("Base {} schema offset 0x{:x} differs from generated packed offset 0x{:x}\n", base.m_Name.m_szName, base.m_nOffset, nCursor));
		}

		for (std::size_t nPreviousIndex = 0; nPreviousIndex < i; ++nPreviousIndex) {
			const auto&       previous     = record.m_BaseClasses[nPreviousIndex];
			const std::size_t nPreviousEnd = previous.m_nOffset + previous.m_nSize;
			if (std::max(base.m_nOffset, previous.m_nOffset) < std::min(nSchemaEnd, nPreviousEnd)) {
				lg::Warn("emitter", "direct bases '{}' and '{}' overlap in class '{}'", previous.m_Name.m_szName, base.m_Name.m_szName,
				         record.m_Name.m_szName);
				break;
			}
		}

		nCursor += base.m_nSize;
	}

	return nCursor;
}

std::size_t shade::codegen::CCppEmitter::Fields(const schema::SchemaClassRecord_t& record, std::size_t nCursor) {
	const schema::SchemaClassFieldRecord_t* pPreviousField = nullptr;
	for (const auto& field : record.m_Fields) {
		if (field.m_nSize == 0) {
			lg::Warn("emitter", "field '{}' in class '{}' has zero size; skipping it", field.m_szName, record.m_Name.m_szName);
			pPreviousField = nullptr;
			continue;
		}

		const std::size_t nEnd = field.m_nOffset + field.m_nSize;
		if (field.m_nOffset > record.m_Layout.m_nSize || nEnd > record.m_Layout.m_nSize)
			lg::Warn("emitter", "field '{}' has a range outside class '{}'", field.m_szName, record.m_Name.m_szName);

		const bool bSharesBitfieldStorage = pPreviousField && field.m_nBitWidth != 0 && pPreviousField->m_nBitWidth != 0 &&
		                                    field.m_nOffset == pPreviousField->m_nOffset && field.m_nSize == pPreviousField->m_nSize;

		if (field.m_nOffset > nCursor) {
			m_Generator.Pad("std::uint8_t", nCursor, field.m_nOffset - nCursor);
			nCursor = field.m_nOffset;
		} else if (field.m_nOffset < nCursor && !bSharesBitfieldStorage)
			lg::Warn("emitter", "field '{}' overlaps an earlier range in class '{}'; emitting best-effort layout", field.m_szName, record.m_Name.m_szName);

		const auto generatedTypeSize = m_Formatter.GetGeneratedSize(field.m_Type);
		if (generatedTypeSize && *generatedTypeSize != field.m_nSize && field.m_nBitWidth == 0) {
			const std::string typeName = m_Formatter.FormatType(field.m_Type);
			lg::Warn("emitter", "field '{}' in class '{}' has schema size 0x{:x}, but generated C++ type '{}' has size 0x{:x}; using byte storage",
			         field.m_szName, record.m_Name.m_szName, field.m_nSize, typeName, *generatedTypeSize);
			m_Generator.Comment(std::format("Original type '{}' replaced with byte storage: generated size 0x{:x}, schema field size 0x{:x}\n", typeName,
			                                *generatedTypeSize, field.m_nSize));
			m_Generator.Declaration(std::format("std::uint8_t {}[0x{:x}]", field.m_szName, field.m_nSize), field.m_nOffset, field.m_nSize);
		} else {
			m_Generator.Declaration(m_Formatter.FormatDeclaration(field.m_Type, field.m_szName, field.m_nSize), field.m_nOffset, field.m_nSize,
			                        field.m_nBitWidth);
		}

		if (!bSharesBitfieldStorage)
			nCursor = nCursor + field.m_nSize;

		pPreviousField = &field;
	}

	if (nCursor < record.m_Layout.m_nSize) {
		m_Generator.Pad("std::uint8_t", nCursor, record.m_Layout.m_nSize - nCursor);
		nCursor = record.m_Layout.m_nSize;
	} else if (nCursor > record.m_Layout.m_nSize)
		lg::Warn("emitter", "member ranges exceed declared size of class '{}'", record.m_Name.m_szName);

	return nCursor;
}

void shade::codegen::CCppEmitter::Class(const schema::SchemaClassRecord_t& record) {
	ClassParameters(record);
	const std::string_view szClassName = record.m_Name.m_szName;

	std::vector<std::string> bases;
	bases.reserve(record.m_BaseClasses.size());
	for (const auto& base : record.m_BaseClasses)
		bases.push_back(m_Formatter.FormatName(base.m_Name));

	std::size_t generatedSize = 0;

	m_Generator.Pragma("pack(push, 1)");
	if (record.m_eType == schema::ESchemaClassType::STRUCT)
		m_Generator.Struct(szClassName, bases, [&] { generatedSize = Fields(record, BaseCursor(record)); });
	else
		m_Generator.Class(szClassName, bases, [&] { generatedSize = Fields(record, BaseCursor(record)); });

	m_Generator.NewLine();
	m_Generator.Pragma("pack(pop)").NewLine();

	DataMapFields(record.m_DataMapFields);
	const bool hasZeroSizedBase = std::ranges::any_of(record.m_BaseClasses, [](const auto& base) { return base.m_nSize == 0; });
	if (record.m_Layout.m_nSize != 0 && generatedSize == record.m_Layout.m_nSize && !hasZeroSizedBase) {
		m_Generator.StaticAssert(szClassName, record.m_Layout.m_nSize);
	} else {
		lg::Warn("emitter", "size assertion for '{}' omitted: generated packed cursor is 0x{:x}, schema size is 0x{:x}", record.m_Name.m_szName,
		         generatedSize, record.m_Layout.m_nSize);
		m_Generator.Comment(
		    std::format("Size assertion omitted: generated packed cursor is 0x{:x}, schema size is 0x{:x}\n", generatedSize, record.m_Layout.m_nSize));
	}
}

void shade::codegen::CCppEmitter::Enum(const schema::SchemaEnumRecord_t& record) {
	if (!m_Formatter.IsValidEnumUnderlyingType(record.m_UnderlyingType)) {
		lg::Warn("emitter", "enum '{}::{}' has an invalid underlying type; skipping it", record.m_Name.m_szModule, record.m_Name.m_szName);
		return;
	}

	m_Generator
	    .Enum(record.m_Name.m_szName, m_Formatter.FormatType(record.m_UnderlyingType), EEnumStyle::Scoped,
	          [&] {
		          for (std::size_t index = 0; index < record.m_Values.size(); ++index) {
			          const auto& value = record.m_Values[index];
			          m_Generator.EnumField(value.m_szName, value.m_nValue, index + 1 == record.m_Values.size());
		          }
	          })
	    .NewLine();
}

void shade::codegen::CCppEmitter::AtomicTemplate(const schema::SchemaAtomicRecord_t& record, bool includeDefaultArgument) {
	switch (record.m_eType) {
	case schema::ESchemaAtomicType::PLAIN:
		break;
	case schema::ESchemaAtomicType::T:
		m_Generator.Template({ ETemplateType::T });
		break;
	case schema::ESchemaAtomicType::COLLECTION_OF_T:
		if (HasFixedBufferCountParameter(record))
			m_Generator.Template({ ETemplateType::T, includeDefaultArgument ? ETemplateType::IntegerDefaultZero : ETemplateType::Integer });
		else
			m_Generator.Template({ ETemplateType::T });
		break;
	case schema::ESchemaAtomicType::TT:
		m_Generator.Template({ ETemplateType::T, ETemplateType::T });
		break;
	case schema::ESchemaAtomicType::I:
		m_Generator.Template({ ETemplateType::Integer });
		break;
	case schema::ESchemaAtomicType::INVALID:
		break;
	}
}

void shade::codegen::CCppEmitter::AtomicForwardDeclarations(std::span<const schema::SchemaAtomicRecord_t> records) {
	bool emitted = false;
	for (const auto& record : records) {
		if (record.m_eType == schema::ESchemaAtomicType::INVALID)
			continue;
		AtomicTemplate(record, true);
		m_Generator.ClassForwardDeclaration(record.m_szName);
		emitted = true;
	}
	if (emitted)
		m_Generator.NewLine();
}

std::string shade::codegen::CCppEmitter::FormatAtomicName(const schema::SchemaAtomicRecord_t&     record,
                                                          const schema::SchemaAtomicParameters_t& parameters) const {
	return std::visit(
	    [&]<typename T>(const T& value) {
		    using Value_t = std::remove_cvref_t<T>;
		    if constexpr (std::same_as<Value_t, std::monostate>)
			    return record.m_szName;

		    else if constexpr (std::same_as<Value_t, schema::SchemaAtomicTypeParameter_t>)
			    return std::format("{}<{}>", record.m_szName, m_Formatter.FormatType(value.m_Type));

		    else if constexpr (std::same_as<Value_t, schema::SchemaAtomicCollectionParameters_t>) {
			    std::string result = std::format("{}<{}", record.m_szName, m_Formatter.FormatType(value.m_ElementType));
			    if (value.m_nFixedBufferCount != 0)
				    result += std::format(", {}", value.m_nFixedBufferCount);
			    result += '>';
			    return result;
		    } else if constexpr (std::same_as<Value_t, schema::SchemaAtomicTwoTypeParameters_t>)
			    return std::format("{}<{}, {}>", record.m_szName, m_Formatter.FormatType(value.m_FirstType), m_Formatter.FormatType(value.m_SecondType));

		    else
			    return std::format("{}<{}>", record.m_szName, value.m_nValue);
	    },
	    parameters);
}

void shade::codegen::CCppEmitter::Atomic(const schema::SchemaAtomicRecord_t& record) {
	if (!record.m_DefaultLayout || record.m_eType == schema::ESchemaAtomicType::INVALID)
		return;

	AtomicTemplate(record, false);

	const std::span<const std::string> noBases;
	m_Generator
	    .Class(record.m_szName, noBases,
	           [&] {
		           if (record.m_DefaultLayout->m_nSize != 0)
			           m_Generator.Pad("std::uint8_t", 0, record.m_DefaultLayout->m_nSize);
	           })
	    .NewLine()
	    .NewLine();

	for (std::size_t index = 0; index < record.m_Specializations.size(); ++index) {
		const auto& specialization = record.m_Specializations[index];
		if (!specialization.m_LayoutOverride)
			continue;
		if (m_Formatter.IsAtomicInvalidByValue(specialization.m_Parameters)) {
			lg::Warn("emitter", "atomic '{}' specialization {} has an invalid by-value parameter; skipping its C++ override", record.m_szName, index);
			continue;
		}

		m_Generator.TemplateSpecialization();
		m_Generator
		    .Class(FormatAtomicName(record, specialization.m_Parameters), noBases,
		           [&] {
			           if (specialization.m_LayoutOverride->m_nSize != 0)
				           m_Generator.Pad("std::uint8_t", 0, specialization.m_LayoutOverride->m_nSize);
		           })
		    .NewLine()
		    .NewLine();
	}
}
