#include "ida_emitter.hpp"

#include <algorithm>
#include <format>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_set>
#include <vector>

#include "generator.hpp"
#include "typeformatter.hpp"

#include "utils/debug.hpp"

namespace {
	using namespace shade;

	/**
	 * @brief Returns dependency map keys in lexicographical order.
	 *
	 * @param dependencies A `const schema::SchemaDependencyMap_t&`.
	 * @return A `std::vector<std::string>`.
	 */
	[[nodiscard]] std::vector<std::string> SortedKeys(const schema::SchemaDependencyMap_t& dependencies) {
		std::vector<std::string> keys;
		keys.reserve(dependencies.size());

		for (const auto& [key, _] : dependencies)
			keys.push_back(key);

		std::ranges::sort(keys);

		return keys;
	}

	/**
	 * @brief Returns string set values in lexicographical order.
	 *
	 * @param values A `const std::unordered_set<std::string>&`.
	 * @return A `std::vector<std::string>`.
	 */
	[[nodiscard]] std::vector<std::string> SortedValues(const std::unordered_set<std::string>& values) {
		std::vector<std::string> result(values.begin(), values.end());
		std::ranges::sort(result);
		return result;
	}
} // namespace

void shade::codegen::CIdaEmitter::Prologue() {
	m_Generator.StartBlockComment()
	    .NewLine()
	    .Comment(" * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.\n")
	    .Comment(" * This file may be used for educational purposes only.\n")
	    .Comment(" ")
	    .EndBlockComment()
	    .NewLine()
	    .NewLine();

	m_Generator.StartBlockComment()
	    .NewLine()
	    .Comment(" * Link to the SDK generator: https://github.com/arisuwine/shadegenerator\n")
	    .Comment(" * Link to the SDK generator developer: https://github.com/arisuwine\n")
	    .Comment(" ")
	    .EndBlockComment()
	    .NewLine()
	    .NewLine();
}

void shade::codegen::CIdaEmitter::ForwardDeclarations(const schema::SchemaDependencies_t& dependencies) {
	const auto modules = SortedKeys(dependencies.m_Declarations);
	for (std::size_t moduleIndex = 0; moduleIndex < modules.size(); ++moduleIndex) {
		const auto& module = modules[moduleIndex];
		m_Generator.Comment(std::format("Forward declarations: {}\n", module.empty() ? "<global>" : module));

		for (const auto& name : SortedValues(dependencies.m_Declarations.at(module))) {
			const schema::SchemaTypeName_t qualifiedName{ module, name };
			const auto                     formatted = m_Formatter.FormatName(qualifiedName);
			if (m_Syntax == EIdaSyntax::C || std::string_view(name).ends_with("_t"))
				m_Generator.StructForwardDeclaration(formatted);
			else
				m_Generator.ClassForwardDeclaration(formatted);
		}

		if (moduleIndex + 1 != modules.size())
			m_Generator.NewLine();
	}
	if (!modules.empty())
		m_Generator.NewLine();
}

void shade::codegen::CIdaEmitter::ClassParameters(const schema::SchemaClassRecord_t& record) {
	m_Generator.StartBlockComment().Comment(" Class Parameters\n");
	m_Generator.Comment(std::format(" * Size: 0x{:x}\n", record.m_Layout.m_nSize));
	m_Generator.Comment(std::format(" * Alignment: 0x{:x}\n", record.m_Layout.m_nAlignment));

	const std::uint32_t flags = record.m_eFlags;
	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_HAS_VTABLE)
		m_Generator.Comment(" * Has VTable\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_IS_ABSTRACT)
		m_Generator.Comment(" * Abstract Class\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_HAS_TRIVIAL_CONSTRUCTOR)
		m_Generator.Comment(" * Has Trivial Constructor\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_HAS_TRIVIAL_DESTRUCTOR)
		m_Generator.Comment(" * Has Trivial Destructor\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_CONSTRUCT_ALLOWED)
		m_Generator.Comment(" * Construct Allowed\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_CONSTRUCT_DISALLOWED)
		m_Generator.Comment(" * Construct Disallowed\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_MODULE_LOCAL_TYPE_SCOPE)
		m_Generator.Comment(" * Module Local Type Scope\n");

	if (flags & schema::ESchemaClassFlags::SCHEMA_CLASS_GLOBAL_TYPE_SCOPE)
		m_Generator.Comment(" * Global Type Scope\n");

	m_Generator.Comment(" ").EndBlockComment().NewLine();
}

void shade::codegen::CIdaEmitter::DataMapFields(std::span<const schema::SchemaDataMapFieldRecord_t> fields) {
	if (fields.empty()) {
		m_Generator.Comment("No unique data map fields\n\n");
		return;
	}

	m_Generator.StartBlockComment().Comment(" Data Map Fields\n");
	for (const auto& field : fields) {
		const auto declaration = m_Formatter.FormatDeclaration(field.m_Type, field.m_szName, field.m_nSizeInBytes);
		m_Generator.Comment(std::format(" * {}; // Offset: 0x{:x}, Size: 0x{:x}, Size In Bytes: 0x{:x}\n", declaration, field.m_nOffset, field.m_nSize,
		                                field.m_nSizeInBytes));
	}
	m_Generator.Comment(" ").EndBlockComment().NewLine().NewLine();
}

std::size_t shade::codegen::CIdaEmitter::CppBaseCursor(const schema::SchemaClassRecord_t& record) {
	std::size_t nSchemaCursor    = 0;
	std::size_t nGeneratedCursor = 0;

	for (std::size_t i = 0; i < record.m_BaseClasses.size(); ++i) {
		const auto&       base       = record.m_BaseClasses[i];
		const std::size_t nSchemaEnd = base.m_nOffset + base.m_nSize;

		if (base.m_nOffset > record.m_Layout.m_nSize || nSchemaEnd > record.m_Layout.m_nSize)
			lg::Warn("emitter", "base '{}' has a range outside class '{}'", base.m_Name.m_szName, record.m_Name.m_szName);

		if (base.m_nOffset != nGeneratedCursor) {
			lg::Warn("emitter", "base '{}' in '{}' has schema offset 0x{:x}, but packed C++ inheritance places it at expected offset 0x{:x}",
			         base.m_Name.m_szName, record.m_Name.m_szName, base.m_nOffset, nGeneratedCursor);
			m_Generator.Comment(std::format("Base {} schema offset 0x{:x} differs from generated packed offset 0x{:x}\n",
			                                m_Formatter.FormatName(base.m_Name), base.m_nOffset, nGeneratedCursor));
		}

		for (std::size_t nPreviousIndex = 0; nPreviousIndex < i; ++nPreviousIndex) {
			const auto&       previous     = record.m_BaseClasses[nPreviousIndex];
			const std::size_t nPreviousEnd = previous.m_nOffset + previous.m_nSize;

			if (std::max(base.m_nOffset, previous.m_nOffset) < std::min(nSchemaEnd, nPreviousEnd)) {
				lg::Warn("emitter", "direct bases '{}' and '{}' overlap in class '{}'", previous.m_Name.m_szName, base.m_Name.m_szName,
				         record.m_Name.m_szName);
				break;
			}
		}

		nSchemaCursor    = std::max(nSchemaCursor, nSchemaEnd);
		nGeneratedCursor = nGeneratedCursor + base.m_nSize;
	}

	return nSchemaCursor;
}

std::size_t shade::codegen::CIdaEmitter::CBaseFields(const schema::SchemaClassRecord_t& record) {
	std::size_t nCursor = 0;
	for (std::size_t index = 0; index < record.m_BaseClasses.size(); ++index) {
		const auto&       base = record.m_BaseClasses[index];
		const std::size_t nEnd = base.m_nOffset + base.m_nSize;
		if (base.m_nOffset > record.m_Layout.m_nSize || nEnd > record.m_Layout.m_nSize)
			lg::Warn("emitter", "base '{}' has a range outside class '{}'", base.m_Name.m_szName, record.m_Name.m_szName);

		if (base.m_nOffset > nCursor) {
			m_Generator.Pad("uint8_t", nCursor, base.m_nOffset - nCursor);
			nCursor = base.m_nOffset;
		} else if (base.m_nOffset < nCursor)
			lg::Warn("emitter", "base '{}' overlaps an earlier base range in class '{}'; emitting best-effort layout", base.m_Name.m_szName,
			         record.m_Name.m_szName);

		m_Generator.Field(m_Formatter.FormatName(base.m_Name), std::format("baseclass_{}", index), base.m_nOffset, base.m_nSize);

		nCursor = std::max(nCursor, nEnd);
	}

	return nCursor;
}

std::size_t shade::codegen::CIdaEmitter::Fields(const schema::SchemaClassRecord_t& record, std::size_t nCursor) {
	const schema::SchemaClassFieldRecord_t* pPreviousField = nullptr;
	for (const auto& field : record.m_Fields) {
		if (field.m_nSize == 0) {
			lg::Warn("emitter", "field '{}' in class '{}' has zero size; skipping it", field.m_szName, record.m_Name.m_szName);
			pPreviousField = nullptr;
			continue;
		}

		const std::size_t nEnd = field.m_nOffset + field.m_nSize;
		if (field.m_nOffset > record.m_Layout.m_nSize || nEnd > record.m_Layout.m_nSize)
			lg::Warn("emitter", "field '{}' has a range outside class '{}'", field.m_szName, record.m_Name.m_szName);

		const bool bSharesBitfieldStorage = pPreviousField && field.m_nBitWidth != 0 && pPreviousField->m_nBitWidth != 0 &&
		                                    field.m_nOffset == pPreviousField->m_nOffset && field.m_nSize == pPreviousField->m_nSize;
		if (field.m_nOffset > nCursor) {
			m_Generator.Pad("uint8_t", nCursor, field.m_nOffset - nCursor);
			nCursor = field.m_nOffset;
		} else if (field.m_nOffset < nCursor && !bSharesBitfieldStorage)
			lg::Warn("emitter", "field '{}' overlaps an earlier range in class '{}'; emitting best-effort layout", field.m_szName, record.m_Name.m_szName);

		m_Generator.Declaration(m_Formatter.FormatDeclaration(field.m_Type, field.m_szName, field.m_nSize), field.m_nOffset, field.m_nSize,
		                        field.m_nBitWidth);
		if (!bSharesBitfieldStorage)
			nCursor = std::max(nCursor, nEnd);

		pPreviousField = &field;
	}

	if (nCursor < record.m_Layout.m_nSize) {
		m_Generator.Pad("uint8_t", nCursor, record.m_Layout.m_nSize - nCursor);
		nCursor = record.m_Layout.m_nSize;
	} else if (nCursor > record.m_Layout.m_nSize)
		lg::Warn("emitter", "member ranges exceed declared size of class '{}'", record.m_Name.m_szName);

	return nCursor;
}

void shade::codegen::CIdaEmitter::Class(const schema::SchemaClassRecord_t& record) {
	ClassParameters(record);

	const auto name = m_Formatter.FormatName(record.m_Name);
	if (m_Syntax == EIdaSyntax::CPP) {
		std::vector<std::string> bases;
		bases.reserve(record.m_BaseClasses.size());
		for (const auto& base : record.m_BaseClasses)
			bases.push_back(m_Formatter.FormatName(base.m_Name));

		const auto cursor = CppBaseCursor(record);
		if (record.m_eType == schema::ESchemaClassType::STRUCT)
			m_Generator.Struct(name, bases, [&] { Fields(record, cursor); });
		else
			m_Generator.Class(name, bases, [&] { Fields(record, cursor); });
	} else {
		const std::span<const std::string> noBases;
		m_Generator.Struct(name, noBases, [&] { Fields(record, CBaseFields(record)); });
	}
	m_Generator.NewLine();

	DataMapFields(record.m_DataMapFields);
}

void shade::codegen::CIdaEmitter::Enum(const schema::SchemaEnumRecord_t& record) {
	if (!m_Formatter.IsValidEnumUnderlyingType(record.m_UnderlyingType)) {
		lg::Warn("emitter", "enum '{}::{}' has an invalid underlying type; skipping it", record.m_Name.m_szModule, record.m_Name.m_szName);
		return;
	}

	const auto emitValues = [&] {
		for (std::size_t index = 0; index < record.m_Values.size(); ++index) {
			const auto& value = record.m_Values[index];
			m_Generator.EnumField(m_Formatter.FormatEnumeratorName(record.m_Name, value.m_szName), value.m_nValue, index + 1 == record.m_Values.size());
		}
	};

	const auto name = m_Formatter.FormatName(record.m_Name);
	m_Generator.Enum(name, m_Formatter.FormatType(record.m_UnderlyingType), EEnumStyle::Unscoped, emitValues).NewLine().NewLine();
}

void shade::codegen::CIdaEmitter::Atomic(const schema::SchemaAtomicRecord_t& record) {
	if (record.m_eType == schema::ESchemaAtomicType::INVALID)
		return;

	const std::span<const std::string> noBases;
	auto emit = [&](const schema::SchemaAtomicParameters_t& parameters, const std::optional<schema::SchemaLayout_t>& overrideLayout,
	                std::size_t specializationIndex) {
		const auto name = m_Formatter.FormatAtomicName(record.m_szName, parameters);
		if (name == "void") {
			lg::Warn("emitter", "atomic '{}' specialization {} has an invalid by-value parameter; skipping it", record.m_szName, specializationIndex);
			return;
		}

		const auto layout = overrideLayout ? overrideLayout : record.m_DefaultLayout;
		if (!layout) {
			lg::Warn("emitter", "atomic '{}' specialization {} has no effective layout; skipping it", record.m_szName, specializationIndex);
			return;
		}

		m_Generator
		    .Struct(name, noBases,
		            [&] {
			            if (layout->m_nSize != 0)
				            m_Generator.Pad("uint8_t", 0, layout->m_nSize);
		            })
		    .NewLine();
	};

	if (record.m_eType == schema::ESchemaAtomicType::PLAIN) {
		emit(std::monostate{}, std::nullopt, 0);
		return;
	}

	for (std::size_t index = 0; index < record.m_Specializations.size(); ++index) {
		const auto& specialization = record.m_Specializations[index];
		emit(specialization.m_Parameters, specialization.m_LayoutOverride, index);
	}
}
